RPI_USER_AGENT = "Raspberry Pi WS"
SITE_SERVER_ADDRESS = "192.168.1.125:8001"
SITE_USER_AGENT = "Raspberry Site"
HMAC_TOKEN = "super secret token"

WS_SERVER_IP = 'vm-linux'
WS_HTTP_PORT = 8090
WS_PORT = 9000
WS_HTTP_SSL = False
WS_USE_SSL = False